server:
    port: ${CONFIG_SERVER_PORT}

spring:
    application:
        name: config-server

    cloud:
        config:
            server:
                enabled: true
                native:
                    search-locations:
                        - classpath:/config
    profiles:
        active: native

eureka:
    client:
        registerWithEureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}
    instance:
        prefer-ip-address: true

# Actuator
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
    
    info:
        env:
            enabled: true
  
info:
    app:
        name: Config Server
        description: A Config Server
        version: 1.0.0
    company:
        name: Turismo
    build:
        time: ${BUILD_TIME:2024-08-21T12:30:00Z}
