spring:
    application:
        name: purchase-microservice
        
server:
    port: 8083

info:
    app:
        name: Purchase Microservice
        description: Purchase Microservice
        version: 1.0.0
    company:
        name: Turismo
    build:
        time: ${BUILD_TIME:2024-08-21T12:30:00Z}