spring:
  application:
    name: user-microservice
  datasource:
    url: ${DB_MS_USER_URL}

server:
  port: ${USER_SERVER_PORT}

eureka:
  instance:
    preferIpAddress: false
    hostname: user-microservice
    instance-id: user-microservice

info:
    app:
        name: User Microservice
        description: User Microservice
        version: 1.0.0
    company:
        name: Turismo
    build:
        time: ${BUILD_TIME:2024-08-21T12:30:00Z}