spring:
    application:
        name: user-microservice
        
server:
    port: 8081

info:
    app:
        name: User Microservice
        description: User Microservice
        version: 1.0.0
    company:
        name: Turismo
    build:
        time: ${BUILD_TIME:2024-08-21T12:30:00Z}