spring:
  application:
    name: gateway-server
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET} # Secreto del cliente configurado en Keycloak
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "${API_GATEWAY_URL}/login/oauth2/code/${KEYCLOAK_CLIENT_ID}" # URL de redirección al API Gateway
            client-authentication-method: basic
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM} # Cambia <KEYCLOAK_HOST> y <REALM_NAME>
            user-name-attribute: preferred_username
  cloud:
    gateway:
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/usuarios/**, /credenciales/**

        - id: service-microservice
          uri: lb://service-microservice
          predicates:
            - Path=/servicios/**, /actividad/**, /alimentacion/**, /calificacion/**, /hospedaje/**, /transporte/**, /voluntariado/**

        - id: purchase-microservice
          uri: lb://purchase-microservice
          predicates:
            - Path=/carrito/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: ${API_GATEWAY_SERVER_PORT}

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    preferIpAddress: false
    hostname: api-gateway
    instance-id: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Turismo API Gateway
    description: Gateway server
    version: 1.0.0
  company:
    name: Turismo
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}

logging:
  level:
    org:
      springframework:
        cloud: 
          gateway: DEBUG
        web: DEBUG 
        security: DEBUG

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}