spring:
    application:
        name: gateway
    cloud:
        gateway:
        # Integration with eureka to automatically discover all the routes of the microservices
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
        
server:
    port: 8080

eureka:
    client:
        registerWithEureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true


# Actuator
management:
    endpoints:
        web:
            exposure:
                include: "*"

    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true
        
    info:
        env:
            enabled: true

info:
    app:
        name: Gateway Server
        description: Gateway server
        version: 1.0.0
    company:
        name: Turismo
    build:
        time: ${BUILD_TIME:2024-08-21T12:30:00Z}