GET http://localhost:8085/service-microservice/service/hello
###
GET http://localhost:8085/user-microservice/user/hello
###

GET http://localhost:8085/cart-microservice/cart/hello
###

GET http://localhost:8085/review-microservice/review/hello
###