spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      # Integration with Eureka to discover all the routes
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:9988/eureka/  # Nueva URL del servidor Eureka
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

  info:
    env:
      enabled: true

# App metadata
info:
  app:
    name: Gateway server Taller
    description: Gateway server para el Taller
    version: 1.0.0
  company:
    name: MS Grupo
    contact:
      email: support@mycompany.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
