server:
  # To avoid colliding with other apps in port 8080
  port: 8081

# App metadata
info:
  app:
    name: user-microservice
    description: Microservicio de Usuarios
    version: 1.0.0
  company:
    name: Epic Games
    contact:
      email: jemirouseche@hotmail.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}